# Generated by Django 5.2.8 on 2025-12-01 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='icon_type',
            field=models.CharField(choices=[('recycle', '♻️ Reciclaje General'), ('plastic', '🧴 Plástico'), ('glass', '🍾 Vidrio'), ('can', '🥫 Lata'), ('box', '📦 Cartón/Caja'), ('shirt', '👕 Ropa'), ('bag', '🛍️ Bolsa')], default='recycle', max_length=50),
        ),
    ]
